name: Linux

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/linux.yaml'
      - 'cmake/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'

  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/linux.yaml'
      - 'cmake/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          python3-dev \
          python3-numpy \
          libgtest-dev \
          libgmock-dev \
          libgoogle-glog-dev \
          clang-format \
          lcov \
          libyaml-cpp-dev \
          nlohmann-json3-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_Fortran_COMPILER=gfortran \
          ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        cd build
        cmake --build . --target coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./build/coverage
        flags: linux
        name: linux-coverage
        fail_ci_if_error: true 