name: macOS

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/macos.yml'
      - 'cmake/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/macos.yml'
      - 'cmake/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        # Install gfortran from gcc
        brew install gcc@13
        # Create gfortran symlink
        sudo ln -sf /usr/local/bin/gfortran-13 /usr/local/bin/gfortran
        # Install other dependencies
        brew install \
          cmake \
          ninja \
          python \
          numpy \
          googletest \
          glog \
          llvm \
          lcov

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        # Use specific gfortran version
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_Fortran_COMPILER=/usr/local/bin/gfortran-13 \
          ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    # Coverage upload temporarily disabled until coverage generation is properly configured
    # - name: Generate coverage report
    #   run: |
    #     cd build
    #     lcov --capture --directory . --output-file coverage.info
    #     lcov --remove coverage.info '/usr/*' --output-file coverage.info
    
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     files: ./build/coverage.info
    #     flags: macos
    #     name: macos-coverage
    #     fail_ci_if_error: true 